import type { Metadata } from 'next';
import './globals.css';
import Provider from '@/hooks/provider';
import RootLayoutClient from './layout.client';
import Logo from '@/components/logo';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Provider>
          <RootLayoutClient>
            <div
              id="_next"
              className={
                'flex h-screen w-full flex-col bg-[url(https://images.unsplash.com/photo-1568528139106-c295280e4757?q=80&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bW91bnRhaW4lMjBhdCUyMG5pZ2h0fGVufDB8fDB8fHww)] bg-cover'
              }
            >
              <Link href={'/'} className="mx-auto mt-2 w-max">
                <Logo className="h-8 w-32" />
              </Link>
              {children}
            </div>
          </RootLayoutClient>
        </Provider>
      </body>
    </html>
  );
}
